/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cake.shop.gui;

/**
 *
 * @author Maxinne Santico 1084694
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForFrame = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        tabsPanel = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        orderingPanel = new javax.swing.JPanel();
        cakeSizesLabel = new javax.swing.JLabel();
        cakeShapesLabel = new javax.swing.JLabel();
        cakeFlavoursLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        cartScrollPane = new javax.swing.JScrollPane();
        cartTextArea = new javax.swing.JTextArea();
        cakeSizeComboBox = new javax.swing.JComboBox<>();
        cakeShapesComboBox = new javax.swing.JComboBox<>();
        cakeFlavoursComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        quantityTrackerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        cartLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userPasswordField = new javax.swing.JPasswordField();
        continueBttn = new javax.swing.JButton();
        backBttn = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phNoLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phNoTextField = new javax.swing.JTextField();
        delOrPicComboBox = new javax.swing.JComboBox<>();
        delOrPicLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        bkButton = new javax.swing.JButton();
        conBtnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CC CAKES");
        setBackground(new java.awt.Color(0, 102, 102));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelForFrame.setBackground(new java.awt.Color(255, 255, 255));
        panelForFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setText("CC CAKES");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(titleLabel)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(15, 15, 15))
        );

        panelForFrame.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 110));

        tabsPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabsPanel.setBorder(null);
        tabsPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxin\\Desktop\\home page.jpg")); // NOI18N
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 29, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONTINUE");
        homePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 411, -1, 38));

        tabsPanel.addTab("Home", homePanel);

        orderingPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        orderingPanel.setLayout(null);

        cakeSizesLabel.setBackground(new java.awt.Color(255, 255, 255));
        cakeSizesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeSizesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeSizesLabel.setText("Cake Sizes:");
        orderingPanel.add(cakeSizesLabel);
        cakeSizesLabel.setBounds(90, 50, 96, 30);

        cakeShapesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeShapesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeShapesLabel.setText("Cake Shapes:");
        orderingPanel.add(cakeShapesLabel);
        cakeShapesLabel.setBounds(80, 140, 120, 30);

        cakeFlavoursLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeFlavoursLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeFlavoursLabel.setText("Cake Flavours:");
        orderingPanel.add(cakeFlavoursLabel);
        cakeFlavoursLabel.setBounds(80, 230, 130, 30);

        quantityLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityLabel.setText("Quantity:");
        orderingPanel.add(quantityLabel);
        quantityLabel.setBounds(100, 330, 90, 30);

        cartTextArea.setBackground(new java.awt.Color(255, 255, 255));
        cartTextArea.setColumns(20);
        cartTextArea.setRows(5);
        cartTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        cartScrollPane.setViewportView(cartTextArea);

        orderingPanel.add(cartScrollPane);
        cartScrollPane.setBounds(370, 70, 270, 340);

        cakeSizeComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderingPanel.add(cakeSizeComboBox);
        cakeSizeComboBox.setBounds(60, 80, 160, 26);

        cakeShapesComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeShapesComboBox.setForeground(new java.awt.Color(255, 255, 255));
        cakeShapesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderingPanel.add(cakeShapesComboBox);
        cakeShapesComboBox.setBounds(60, 170, 160, 26);

        cakeFlavoursComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeFlavoursComboBox.setForeground(new java.awt.Color(255, 255, 255));
        cakeFlavoursComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderingPanel.add(cakeFlavoursComboBox);
        cakeFlavoursComboBox.setBounds(60, 260, 160, 26);

        addButton.setBackground(new java.awt.Color(0, 51, 51));
        addButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("+");
        orderingPanel.add(addButton);
        addButton.setBounds(170, 360, 40, 32);

        subtractButton.setBackground(new java.awt.Color(0, 51, 51));
        subtractButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        subtractButton.setForeground(new java.awt.Color(255, 255, 255));
        subtractButton.setText("-");
        orderingPanel.add(subtractButton);
        subtractButton.setBounds(70, 360, 40, 32);

        quantityTrackerLabel.setBackground(new java.awt.Color(255, 255, 255));
        quantityTrackerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        quantityTrackerLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityTrackerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityTrackerLabel.setText("1");
        orderingPanel.add(quantityTrackerLabel);
        quantityTrackerLabel.setBounds(110, 360, 60, 30);

        backButton.setBackground(new java.awt.Color(0, 51, 51));
        backButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<");
        orderingPanel.add(backButton);
        backButton.setBounds(240, 440, 70, 30);

        continueButton.setBackground(new java.awt.Color(0, 51, 51));
        continueButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText(">");
        orderingPanel.add(continueButton);
        continueButton.setBounds(330, 440, 70, 30);

        cartLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        cartLabel.setForeground(new java.awt.Color(0, 102, 102));
        cartLabel.setText("Your Cart:");
        orderingPanel.add(cartLabel);
        cartLabel.setBounds(370, 50, 80, 20);

        tabsPanel.addTab("Ordering", orderingPanel);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        loginPanel.setLayout(null);

        usernameTextField.setBackground(new java.awt.Color(204, 204, 204));
        usernameTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(0, 51, 51));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        loginPanel.add(usernameTextField);
        usernameTextField.setBounds(310, 190, 200, 30);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Login or create an account to proceed:");
        loginPanel.add(jLabel2);
        jLabel2.setBounds(170, 120, 397, 30);

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 102, 102));
        usernameLabel.setText("Username:");
        loginPanel.add(usernameLabel);
        usernameLabel.setBounds(210, 200, 88, 20);

        passwordLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 102, 102));
        passwordLabel.setText("Password:");
        loginPanel.add(passwordLabel);
        passwordLabel.setBounds(210, 260, 80, 20);

        userPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        userPasswordField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        userPasswordField.setForeground(new java.awt.Color(0, 51, 51));
        loginPanel.add(userPasswordField);
        userPasswordField.setBounds(310, 250, 200, 30);

        continueBttn.setBackground(new java.awt.Color(0, 51, 51));
        continueBttn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        continueBttn.setForeground(new java.awt.Color(255, 255, 255));
        continueBttn.setText("Continue");
        loginPanel.add(continueBttn);
        continueBttn.setBounds(360, 350, 100, 30);

        backBttn.setBackground(new java.awt.Color(0, 51, 51));
        backBttn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backBttn.setText("Back");
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });
        loginPanel.add(backBttn);
        backBttn.setBounds(230, 350, 100, 30);

        tabsPanel.addTab("Login", loginPanel);

        detailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        detailsPanel.setLayout(null);

        firstNameLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(0, 102, 102));
        firstNameLabel.setText("First Name:");
        detailsPanel.add(firstNameLabel);
        firstNameLabel.setBounds(60, 90, 79, 20);

        lastNameLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(0, 102, 102));
        lastNameLabel.setText("Last Name:");
        detailsPanel.add(lastNameLabel);
        lastNameLabel.setBounds(60, 140, 80, 20);

        addressLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(0, 102, 102));
        addressLabel.setText("Address:");
        detailsPanel.add(addressLabel);
        addressLabel.setBounds(60, 190, 80, 20);

        emailLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 102, 102));
        emailLabel.setText("Email Address:");
        detailsPanel.add(emailLabel);
        emailLabel.setBounds(60, 320, 120, 20);

        phNoLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        phNoLabel.setForeground(new java.awt.Color(0, 102, 102));
        phNoLabel.setText("Phone Number:");
        detailsPanel.add(phNoLabel);
        phNoLabel.setBounds(60, 370, 120, 20);

        firstNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        firstNameTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(0, 102, 102));
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        detailsPanel.add(firstNameTextField);
        firstNameTextField.setBounds(190, 90, 240, 22);

        lastNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        lastNameTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(0, 102, 102));
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        detailsPanel.add(lastNameTextField);
        lastNameTextField.setBounds(190, 140, 240, 22);

        emailTextField.setBackground(new java.awt.Color(204, 204, 204));
        emailTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(0, 102, 102));
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        detailsPanel.add(emailTextField);
        emailTextField.setBounds(190, 310, 240, 22);

        phNoTextField.setBackground(new java.awt.Color(204, 204, 204));
        phNoTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        phNoTextField.setForeground(new java.awt.Color(0, 102, 102));
        phNoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        detailsPanel.add(phNoTextField);
        phNoTextField.setBounds(190, 360, 240, 22);

        delOrPicComboBox.setBackground(new java.awt.Color(0, 51, 51));
        delOrPicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        detailsPanel.add(delOrPicComboBox);
        delOrPicComboBox.setBounds(500, 230, 130, 26);

        delOrPicLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        delOrPicLabel.setForeground(new java.awt.Color(0, 102, 102));
        delOrPicLabel.setText("Delivery or Pick Up:");
        detailsPanel.add(delOrPicLabel);
        delOrPicLabel.setBounds(500, 200, 150, 20);

        addressTextArea.setBackground(new java.awt.Color(204, 204, 204));
        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        addressTextArea.setForeground(new java.awt.Color(0, 102, 102));
        addressTextArea.setRows(5);
        addressTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jScrollPane2.setViewportView(addressTextArea);

        detailsPanel.add(jScrollPane2);
        jScrollPane2.setBounds(190, 180, 240, 83);

        bkButton.setBackground(new java.awt.Color(0, 51, 51));
        bkButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        bkButton.setForeground(new java.awt.Color(255, 255, 255));
        bkButton.setText("<");
        detailsPanel.add(bkButton);
        bkButton.setBounds(260, 450, 80, 30);

        conBtnDetails.setBackground(new java.awt.Color(0, 51, 51));
        conBtnDetails.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        conBtnDetails.setForeground(new java.awt.Color(255, 255, 255));
        conBtnDetails.setText(">");
        detailsPanel.add(conBtnDetails);
        conBtnDetails.setBounds(360, 450, 73, 30);

        tabsPanel.addTab("Customer Details", detailsPanel);

        panelForFrame.add(tabsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 550));

        getContentPane().add(panelForFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBttnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backBttn;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bkButton;
    private javax.swing.JComboBox<String> cakeFlavoursComboBox;
    private javax.swing.JLabel cakeFlavoursLabel;
    private javax.swing.JComboBox<String> cakeShapesComboBox;
    private javax.swing.JLabel cakeShapesLabel;
    private javax.swing.JComboBox<String> cakeSizeComboBox;
    private javax.swing.JLabel cakeSizesLabel;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JTextArea cartTextArea;
    private javax.swing.JButton conBtnDetails;
    private javax.swing.JButton continueBttn;
    private javax.swing.JButton continueButton;
    private javax.swing.JComboBox<String> delOrPicComboBox;
    private javax.swing.JLabel delOrPicLabel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel orderingPanel;
    private javax.swing.JPanel panelForFrame;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phNoLabel;
    private javax.swing.JTextField phNoTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityTrackerLabel;
    private javax.swing.JButton subtractButton;
    private javax.swing.JTabbedPane tabsPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
