/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cake.shop.gui;

/**
 *
 * @author maxin
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForFrame = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        tabsPanel = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        orderingPanel = new javax.swing.JPanel();
        cakeSizesLabel = new javax.swing.JLabel();
        cakeShapesLabel = new javax.swing.JLabel();
        cakeFlavoursLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        cartScrollPane = new javax.swing.JScrollPane();
        cartTextArea = new javax.swing.JTextArea();
        cakeSizeComboBox = new javax.swing.JComboBox<>();
        cakeShapesComboBox = new javax.swing.JComboBox<>();
        cakeFlavoursComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        quantityTrackerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        cartLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        customerDetailsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CC CAKES");
        setBackground(new java.awt.Color(0, 102, 102));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelForFrame.setBackground(new java.awt.Color(255, 255, 255));
        panelForFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        panelForFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setText("CC CAKES");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(titleLabel)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(15, 15, 15))
        );

        panelForFrame.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 110));

        tabsPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabsPanel.setBorder(null);
        tabsPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxin\\Desktop\\home page.jpg")); // NOI18N
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 29, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONTINUE");
        homePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 411, -1, 38));

        tabsPanel.addTab("Home", homePanel);

        orderingPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderingPanel.setLayout(null);

        cakeSizesLabel.setBackground(new java.awt.Color(255, 255, 255));
        cakeSizesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeSizesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeSizesLabel.setText("Cake Sizes:");
        orderingPanel.add(cakeSizesLabel);
        cakeSizesLabel.setBounds(90, 50, 96, 30);

        cakeShapesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeShapesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeShapesLabel.setText("Cake Shapes:");
        orderingPanel.add(cakeShapesLabel);
        cakeShapesLabel.setBounds(80, 140, 120, 30);

        cakeFlavoursLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeFlavoursLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeFlavoursLabel.setText("Cake Flavours:");
        orderingPanel.add(cakeFlavoursLabel);
        cakeFlavoursLabel.setBounds(80, 230, 130, 30);

        quantityLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityLabel.setText("Quantity:");
        orderingPanel.add(quantityLabel);
        quantityLabel.setBounds(100, 330, 90, 30);

        cartTextArea.setBackground(new java.awt.Color(255, 255, 255));
        cartTextArea.setColumns(20);
        cartTextArea.setRows(5);
        cartTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        cartScrollPane.setViewportView(cartTextArea);

        orderingPanel.add(cartScrollPane);
        cartScrollPane.setBounds(370, 70, 270, 340);

        cakeSizeComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cakeSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeSizeComboBoxActionPerformed(evt);
            }
        });
        orderingPanel.add(cakeSizeComboBox);
        cakeSizeComboBox.setBounds(60, 80, 160, 26);

        cakeShapesComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeShapesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cakeShapesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeShapesComboBoxActionPerformed(evt);
            }
        });
        orderingPanel.add(cakeShapesComboBox);
        cakeShapesComboBox.setBounds(60, 170, 160, 26);

        cakeFlavoursComboBox.setBackground(new java.awt.Color(0, 51, 51));
        cakeFlavoursComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cakeFlavoursComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeFlavoursComboBoxActionPerformed(evt);
            }
        });
        orderingPanel.add(cakeFlavoursComboBox);
        cakeFlavoursComboBox.setBounds(60, 260, 160, 26);

        addButton.setBackground(new java.awt.Color(0, 51, 51));
        addButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        addButton.setText("+");
        orderingPanel.add(addButton);
        addButton.setBounds(170, 360, 40, 32);

        subtractButton.setBackground(new java.awt.Color(0, 51, 51));
        subtractButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        subtractButton.setForeground(new java.awt.Color(255, 255, 255));
        subtractButton.setText("-");
        orderingPanel.add(subtractButton);
        subtractButton.setBounds(70, 360, 40, 32);

        quantityTrackerLabel.setBackground(new java.awt.Color(255, 255, 255));
        quantityTrackerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        quantityTrackerLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityTrackerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityTrackerLabel.setText("1");
        orderingPanel.add(quantityTrackerLabel);
        quantityTrackerLabel.setBounds(110, 360, 60, 30);

        backButton.setBackground(new java.awt.Color(0, 51, 51));
        backButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<");
        orderingPanel.add(backButton);
        backButton.setBounds(240, 440, 70, 30);

        continueButton.setBackground(new java.awt.Color(0, 51, 51));
        continueButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText(">");
        orderingPanel.add(continueButton);
        continueButton.setBounds(330, 440, 70, 30);

        cartLabel.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        cartLabel.setForeground(new java.awt.Color(0, 102, 102));
        cartLabel.setText("Your Cart:");
        orderingPanel.add(cartLabel);
        cartLabel.setBounds(370, 50, 80, 20);

        tabsPanel.addTab("Ordering", orderingPanel);

        jCheckBox2.setText("jCheckBox2");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jCheckBox2)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        tabsPanel.addTab("Login", loginPanel);

        javax.swing.GroupLayout customerDetailsPanelLayout = new javax.swing.GroupLayout(customerDetailsPanel);
        customerDetailsPanel.setLayout(customerDetailsPanelLayout);
        customerDetailsPanelLayout.setHorizontalGroup(
            customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        customerDetailsPanelLayout.setVerticalGroup(
            customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        tabsPanel.addTab("Customer Details", customerDetailsPanel);

        panelForFrame.add(tabsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 680, 520));

        getContentPane().add(panelForFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cakeSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeSizeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakeSizeComboBoxActionPerformed

    private void cakeShapesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeShapesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakeShapesComboBoxActionPerformed

    private void cakeFlavoursComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeFlavoursComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakeFlavoursComboBoxActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> cakeFlavoursComboBox;
    private javax.swing.JLabel cakeFlavoursLabel;
    private javax.swing.JComboBox<String> cakeShapesComboBox;
    private javax.swing.JLabel cakeShapesLabel;
    private javax.swing.JComboBox<String> cakeSizeComboBox;
    private javax.swing.JLabel cakeSizesLabel;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JTextArea cartTextArea;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel customerDetailsPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel orderingPanel;
    private javax.swing.JPanel panelForFrame;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityTrackerLabel;
    private javax.swing.JButton subtractButton;
    private javax.swing.JTabbedPane tabsPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
