/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cake.shop.gui;

/**
 *
 * @author maxin
 */
public class OrderingPage extends javax.swing.JFrame {

    /**
     * Creates new form OrderingPage
     */
    public OrderingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cakeSizesLabel = new javax.swing.JLabel();
        cakeShapesLabel = new javax.swing.JLabel();
        cakeFlavoursLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cartLabel = new javax.swing.JLabel();
        sizesComboBox = new javax.swing.JComboBox<>();
        shapesComboBox = new javax.swing.JComboBox<>();
        flavoursComboBox = new javax.swing.JComboBox<>();
        quantityLabel = new javax.swing.JLabel();
        addQtyButton = new javax.swing.JButton();
        subtractQtyButton = new javax.swing.JButton();
        quantityTrackerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel1.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setText(" CC CAKES");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 40, 230, 70);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 190, 290, 320);

        cakeSizesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeSizesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeSizesLabel.setText("Cake Sizes:");
        jPanel1.add(cakeSizesLabel);
        cakeSizesLabel.setBounds(60, 170, 100, 23);

        cakeShapesLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeShapesLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeShapesLabel.setText("Cake Shapes:");
        jPanel1.add(cakeShapesLabel);
        cakeShapesLabel.setBounds(60, 250, 120, 23);

        cakeFlavoursLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cakeFlavoursLabel.setForeground(new java.awt.Color(0, 102, 102));
        cakeFlavoursLabel.setText("Cake Flavours:");
        jPanel1.add(cakeFlavoursLabel);
        cakeFlavoursLabel.setBounds(60, 350, 120, 23);

        backButton.setBackground(new java.awt.Color(0, 51, 51));
        backButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(240, 550, 80, 40);

        nextButton.setBackground(new java.awt.Color(0, 51, 51));
        nextButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton);
        nextButton.setBounds(350, 550, 70, 40);

        cartLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cartLabel.setForeground(new java.awt.Color(0, 102, 102));
        cartLabel.setText("Your Cart:");
        jPanel1.add(cartLabel);
        cartLabel.setBounds(520, 130, 79, 20);

        sizesComboBox.setBackground(new java.awt.Color(0, 51, 51));
        sizesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(sizesComboBox);
        sizesComboBox.setBounds(60, 190, 210, 26);

        shapesComboBox.setBackground(new java.awt.Color(0, 51, 51));
        shapesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(shapesComboBox);
        shapesComboBox.setBounds(60, 280, 210, 26);

        flavoursComboBox.setBackground(new java.awt.Color(0, 51, 51));
        flavoursComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(flavoursComboBox);
        flavoursComboBox.setBounds(60, 370, 210, 26);

        quantityLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityLabel.setText("Quantity:");
        jPanel1.add(quantityLabel);
        quantityLabel.setBounds(60, 430, 76, 23);

        addQtyButton.setBackground(new java.awt.Color(0, 51, 51));
        addQtyButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        addQtyButton.setText("+");
        jPanel1.add(addQtyButton);
        addQtyButton.setBounds(150, 460, 37, 30);

        subtractQtyButton.setBackground(new java.awt.Color(0, 51, 51));
        subtractQtyButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        subtractQtyButton.setForeground(new java.awt.Color(255, 255, 255));
        subtractQtyButton.setText("-");
        jPanel1.add(subtractQtyButton);
        subtractQtyButton.setBounds(60, 460, 33, 30);

        quantityTrackerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        quantityTrackerLabel.setForeground(new java.awt.Color(0, 102, 102));
        quantityTrackerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityTrackerLabel.setText("1");
        jPanel1.add(quantityTrackerLabel);
        quantityTrackerLabel.setBounds(90, 450, 60, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQtyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cakeFlavoursLabel;
    private javax.swing.JLabel cakeShapesLabel;
    private javax.swing.JLabel cakeSizesLabel;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JComboBox<String> flavoursComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityTrackerLabel;
    private javax.swing.JComboBox<String> shapesComboBox;
    private javax.swing.JComboBox<String> sizesComboBox;
    private javax.swing.JButton subtractQtyButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
